### ISSUE TITLE
Windows SSH

### ISSUE THREAD

**Issue by ryanseddon** [rsms/ec2-webapp#1]
Since SSH isn't built into Windows (Boo!) it involves a few more steps to SSH into an EC2 instance. I could write a step by step guide that shows how to do it with putty/putty gen etc.

 I'd make it a separate markdown document and just link to it in the INSTALL.md file.

 Let me know and I'll update my fork and do a pull request.

**Comment by rsms** [comment]
That'd be great. Please do.
