### ISSUE TITLE
is there an updated version?

### ISSUE THREAD

**Issue by tobsn** [rsms/ec2-webapp#15]
thanks!

**Comment by rsms** [comment]
Nope. What's broken?

**Comment by tobsn** [comment]
it's 3 years old so I assume it's outdated... ;)

**Comment by rsms** [comment]
Kind of, yeah. I still used it as a manual template two or three months ago the last time though. I guess that if you use a newer version of Ubuntu than this is designed for, you'll face some challenges.

Also, wow. Three years already?! Feels like yesterday, ha ha.
