### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by skilesare** [rsms/ec2-webapp#3]
First of all, thank you for putting this together.  I feel like I'm close and I wouldn't be if not for this guide.

I've followed all the steps on install.md.  At the end I try to curl http://127.0.0.1 and I get:

502 Bad Gateway
<hr><center>nginx/0.7.67</center>

I also don't see anything set up on port 3000.  
(curl: (7) couldn't connect to host)

I tried adding the sample node.js from the node.js site to a file in nodelib called ws.js:

var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(8124, "127.0.0.1");
console.log('Server running at http://127.0.0.1:8124/');

But nothing come sup on port 8124 either.

I really don't know what I'm doing and I've learned a ton from executing the guide.  As best I can tell, I've started both the myapp-httpd and myapp-processor(and maybe this is my mistake, it said optional and optionally so I did both).  Any help would be greatly appreciated.

**Comment by rsms** [comment]
> I tried adding the sample node.js from the node.js site to a file in nodelib called ws.js:

Then you didn't follow the guide. In INSTALL.mv under "Configure & start your services" the first step is to "Your Node.js web server". What that step does is to install, configure and start `myapp-httpd` (bin/myapp-httpd.mv and friends). If you write your own Node.js HTTP server (i.e. don't use the init.d script or the myapp-httpd.mv program provided), you'll have to take necessary actions to make your Node.js HTTP server run on port 3000, preferably only listening on localhost.

Note that the code snippet you pasted above ("[...] a file in nodelib called ws.js") listens on port 8124, not 3000.

**Comment by rsms** [comment]
Just as to double-check everything: If you really installed and started myapp-httpd, try to start the server manually:

```
move /var/myapp/bin/myapp-httpd.mv
```

See if it dies with an error message or no. If not and the program continues to run, you should try (in another terminal):

```
curl 127.0.0.1:3000/user/123
```

**Comment by skilesare** [comment]
Ok...that makes sense.  So do I actually put my code in myapp-httpd.mv?

I appreciate your patience.  I'm trying to learn node and I haven't written any code...I'm just trying to get the point where I can write some code.

**Comment by rsms** [comment]
Yeah, or replace myapp-httpd.mv with a home-rolled web server. However, note that the suggested workflow depends on the functionality of this web server — if it does not support serving static files, you'll have to setup nginx or another fronting web server locally for development (which is rather cumbersome).

If you're not familiar with the Move language, here's all you need to get up to speed: http://movelang.org/
