### ISSUE TITLE
Bad Gateway Revisited

### ISSUE THREAD

**Issue by pbaker** [rsms/ec2-webapp#6]
I have followed your suggestions from a previous post (to restart, then check for a connection on Port 3000).
I suspect the move script may not actually be executing; after adding a few print statements, no visible results.  Can you suggest a debug approach? 
# sudo invoke-rc.d myapp-httpd restart
- stopping myapp-httpd                                                              [ OK ] 
- starting myapp-httpd                                                              [ OK ] 
# curl 127.0.0.1:3000

curl: (7) couldn't connect to host

**Comment by rsms** [comment]
It's basically just a placeholder. I haven't even had the chance to test the html stuff (just a quick "dry written" thing). And I use Move instead of JS, so that's why it's written in Move. You can of course write your Node server in JS or whatever.
